### ISSUE TITLE
Code in repo not working, outdated?

### ISSUE THREAD

**Issue by BlakeOne** [CiaraStrawberry/sdv_controlnet#2]
Oops it looks like the code in this repo has gotten out of sync with your working copy... 

Here are the issues that I've encountered so far: the motion_bucket_ids were on the wrong device resulting in a runtime error, EulerDiscreteScheduler was being imported improperly resulting in another runtime error, and the number of frames is still somewhere hard coded at 16 it seems...

I can try to PR my minimal fixes in but I wonder if it might be simpler and more comprehensive to upload the new, working code files that you're training with?

Either way thanks for sharing your project, it looks really exciting! :)

**Comment by BlakeOne** [comment]
Here's a little PR to show how I fixed the two runtime errors: https://github.com/CiaraStrawberry/sdv_controlnet/pull/3

Although I'm not sure if there might be other parts that are outdated too?

**Comment by CiaraStrawberry** [comment]
Oh it's not done yet, my apologies for not specifying in the readme.
Since yesterday evening it works on my side but i haven't checked for any specifics of my copy that are distinct from the repo so that is likely contributing, i'll compare your pr against those, thanks for that.

**Comment by BlakeOne** [comment]
No worries I understand but I guess I'll keep trying to get it working since I'm impatient and can't wait LOL.. So far I haven't been able to get any decent results yet thou so I'll be super interested to see how you've been doing your training. :)

**Comment by CiaraStrawberry** [comment]
Make sure you train for 20k+ steps at a batch size of like 8 lr 1e-5,
It's working for me so far.

![combined_with_square_image_new_gif](https://github.com/CiaraStrawberry/sdv_controlnet/assets/13116982/307c250c-e58f-43dd-a9cf-47d2289fd668)

Gonna announce on twitter tommorow
